### ISSUE TITLE
Magic numbers

### ISSUE THREAD

**Issue by FelipeJensen** [FarzamMohammadi/learnaholic#3]
https://github.com/FarzamMohammadi/learnaholic/blob/56b81f55646a5998c29413875df029c1ed61db6b/Coding-Problems/CSharp/EnhancedLRUCache/EnhancedLRUCache/LruCache.cs#L46

https://github.com/FarzamMohammadi/learnaholic/blob/56b81f55646a5998c29413875df029c1ed61db6b/Coding-Problems/CSharp/EnhancedLRUCache/EnhancedLRUCache/LruCache.cs#L51

**Comment by FarzamMohammadi** [comment]
also validate string is not empty if TKey is of type string: https://github.com/FarzamMohammadi/learnaholic/blob/56b81f55646a5998c29413875df029c1ed61db6b/Coding-Problems/CSharp/EnhancedLRUCache/EnhancedLRUCache/LruCache.cs#L80C1-L81C1
